version: 0.2

phases:
  install:
    runtime-versions:
       java: openjdk8
  build:
    commands:
       - echo "${CODEBUILD_WEBHOOK_HEAD_REF}"
       - chmod +x ./gradlew
       - aws s3 cp s3://nexuscredentials-cms/maven/settings.xml .
       - mkdir ~/.gradle -p
       - aws s3 cp s3://nexuscredentials-cms/maven/gradle.encrypted.properties ~/.gradle/
       - ./gradlew build --no-daemon
       - ./gradlew publish --no-daemon
